version: '3'

services:
  bitcore_mn1:
    build:
      context: ./docker-bitcored
      dockerfile: ./Dockerfile
    image: bitcored-mn
    container_name: bitcore_mn1
    command:
      -externalip=${EXTERNAL_IP}
      -whitebind=172.21.0.11:8555
      -rpcbind=172.21.0.11
      -maxconnections=32
      -masternodeaddr=${EXTERNAL_IP}:8555
      -masternodeprivkey=${MN1_PRIVKEY}
      -rpcuser=rpc
      -rpcpassword=${MN1_RPC_PWD}
    restart: always
    networks:
      bitcore-net:
        ipv4_address: 172.21.0.11
    ports:
      - 8555:8555
    expose:
      - 8555
      - 8556
    volumes:
      - /home/bitcore_mn1:/data

networks:
  bitcore-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
